OUT+=template
OUT+=template_en
OUT+=anleitung
OUT+=anleitung_en

template_TEX=	tex/commons.tex			\
		tex/acronyms.tex			\
		tex/einleitung.tex			\
		tex/stand_der_technik.tex		\
		tex/konzept.tex				\
		tex/implementierung.tex			\
		tex/ergebnisse.tex			\
		tex/ausblick.tex			\
		tex/appendix0.tex

template_en_TEX=	tex/commons.tex			\
		tex/acronyms_en.tex			\
		tex/einleitung_en.tex			\
		tex/stand_der_technik_en.tex		\
		tex/konzept_en.tex				\
		tex/implementierung_en.tex			\
		tex/ergebnisse_en.tex			\
		tex/ausblick_en.tex			\
		tex/appendix0_en.tex

template_PICS=	pics/TU_Chemnitz_positiv_gruen.pdf	\
		pics/selbstaendigkeitserklaerung.pdf

template_UNIQ=

anleitung_TEX=	tex/acronyms.tex			\
		tex/einleitung.tex			\
		tex/stand_der_technik.tex		\
		tex/konzept.tex				\
		tex/implementierung.tex			\
		tex/ergebnisse.tex			\
		tex/ausblick.tex			\
		tex/appendix0.tex

anleitung_en_TEX=	tex/acronyms_en.tex			\
		tex/einleitung_en.tex			\
		tex/stand_der_technik_en.tex		\
		tex/konzept_en.tex				\
		tex/implementierung_en.tex			\
		tex/ergebnisse_en.tex			\
		tex/ausblick_en.tex			\
		tex/appendix0_en.tex

include ../Makefile.imp
